backend:
  name: git-gateway
  branch: main

media_folder: "/pages/uploads/"
public_folder: "/pages/uploads/"

collections:
  - name: "news"
    label: "뉴스"
    folder: "/content/news/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "카테고리", name: "category", widget: "select", options: ["정치", "사회", "민생", "문화", "칼럼", "공지사항"] }
      - { label: "본문", name: "body", widget: "markdown" }
